global.yeca = [
'estas listo',
'a que se dedica Bad Bunny',
'Cuál es el lugar más frío de la tierra',
'en que año el hombre piso la luna',
'a que se dedica Jackie Chan',
'cuantos minutos tiene una hora',
'cuantos cuartos de kilo hay en un kilo',
'cuantas horas tiene un dia',
'cual es el antonimo de rico',
'como se llama el lugar donde se escriben las notas musicales',
'es lo mismo multiplicar 3x4 que 4x3 - si o no',
'como se llama el triángulo que tiene tres lados iguales',
'que no puede faltar en una oración para que sea completa',
'como se llama quien cuenta la historia de un cuento',
'como se dice en ingles buenas tardes',
'que órgano usamos para respirar',
'como se llama la rayita que ponen encima de la sílaba tónica',
'cuanto es el resultado de 9x9',
'cual es el rio mas largo de Europa',
'a través de que órgano respiran los peces',
'cual es el rio mas largo del mundo',
'por que esta formado el planeta principalmente',
'cual es la capital de Francia',
'de donde se extrae el papel',
'en que continente esta Brasil',
'en que ciudad se encuentra la torre Eiffel',
'quien es el autor de El Quijote',
'cual es el pais mas grande del mundo',
'como se llama el resultado de la multiplicación',
'cual es el animal más rápido del mundo',
'cuantas patas tiene una araña',
'cual es el tercer planeta del sistema solar - en cuanto a distancia del sol',
'que somos los humanos: omnívoros - herbivoros o carnívoros',
'en que año colón descubrió America',
'como se llama la linea imaginaria que divide la tierra por la mitad',
'cual es el rio mas largo del mundo',
'cual es el rio mas largo de España',
'cual es la moneda de Marruecos',
'como se llama la capital de Mongolia',
'por cultivar que producto es conocido Guatemala',
'en que año comenzo la segunda guerra mundial',
'que deporte practicaba Carl Lewis',
'cual es el quinto planeta del sistema solar - en cuanto a la distancia del sol',
'cual es el pais mas poblado de la tierra',
'cual es el metal mas caro del mundo',
'cual es la capital de Suecia',
'que rama de la biologia estudia los animales',
'cual es el nombre de la lengua oficial en china',
'como se llama la estación espacial rusa',
'cual fue el primer metal que empleó el hombre',
'en que lugar del cuerpo se produce la insulina',
'cual es la capital de Irán',
'que instrumento optico permite ver los astros de cerca',
'que es mas pequeño un atomo o una molecula',
'cual es el único mamifero capaz de volar',
'cuantos dientes tiene una persona adulta',
'cual es el pais de nacimiento de Pablo Neruda',
'segun los escritos bíblicos - quien traicionó a Jesus',
'como se llama la ciencia que estudia los mapas',
'quien descubrio la penicilina',
'cuantos dedos tienen los gatos',
'la bandera de jamaica tiene color amarillo - si o no',
'la ballena es un herbívoro- si o no',
'la bandera de México tiene color azul- si o no',
'en que año termino la segunda guerra mundial',
'a que se dedica Justin timberleke - cantante actor o cazador',
'como se llama el proceso por el cual las plantas obtienen alimentos',
'de que esta recubierto el cuerpo de los peces',
'Col es una nota musical - si o no',
'cual es la capital de Dinamarca',
'de que lengua proviene el español',
'Sylvester Stallone es cantante- si o no',
'quien es el protagonista de la pelicula - Rocky ',
'que come el animal que es Carnívoro',
'cual es el pais con mayor porcentaje de budistas',
'cuanto es 5+4-3+6-3+4',
'Justin Bieber es cantante- si o no',
'en ingles como se dice hola',
'Justin Bieber se dedica a pilotear aviones- si o no',
'Do es una nota musical - si o no',
'Re es una nota musical - si o no',
'Fa es una nota musical - si o no',
'Mi es una nota musical - si o no',
'Sol es una nota musical - si o no',
'La es una nota musical - si o no',
'Ca es una nota musical - si o no',
'Sa es una nota musical - si o no',
'Gu es una nota musical - si o no',
'cuantos cuartos de kilo hay en dos kilos',
'cuantos cuartos de kilo hay en tres kilos',
'cuantos cuartos de kilo hay en cuatro kilos',
'cuantos cuartos de kilo hay en cinco kilos',
'cuantos cuartos de kilo hay en seis kilos',
'cuantos cuartos de kilo hay en siete kilos',
'cuantos cuartos de kilo hay en ocho kilos',
'es lo mismo multiplicar 8x4 que 4x1 - si o no',
'es lo mismo multiplicar 1x4 que 4x7 - si o no',
'es lo mismo multiplicar 6x4 que 4x2 - si o no',
'es lo mismo multiplicar 9x4 que 4x6 - si o no',
'es lo mismo multiplicar 2x4 que 4x9 - si o no',
'es lo mismo multiplicar 1x4 que 4x1 - si o no',
'es lo mismo multiplicar 2x4 que 4x2 - si o no',
'es lo mismo multiplicar 3x4 que 4x3 - si o no',
'es lo mismo multiplicar 4x4 que 4x4 - si o no',
'es lo mismo multiplicar 5x4 que 4x5 - si o no',
'cual es el primer planeta del sistema solar - en cuanto a la distancia del sol',
'cual es el segundo planeta del sistema solar - en cuanto a la distancia del sol',
'cual es el cuarto planeta del sistema solar - en cuanto a la distancia del sol',
'cual es el séptimo planeta del sistema solar - en cuanto a la distancia del sol',
'cual es el sexto planeta del sistema solar - en cuanto a la distancia del sol',
'cual es el octavo planeta del sistema solar - en cuanto a la distancia del sol',
'que son los caballos: omnívoros - herbivoros o carnívoros',
'que son los gacelas: omnívoros - herbivoros o carnívoros',
'que son los asnos: omnívoros - herbivoros o carnívoros',
'que son los cebras: omnívoros - herbivoros o carnívoros',
'que son los elefantes: omnívoros - herbivoros o carnívoros',
'que son los hipopótamos: omnívoros - herbivoros o carnívoros',
'que son los tapires: omnívoros - herbivoros o carnívoros',
'que son los osos: omnívoros - herbivoros o carnívoros',
'que son los ratones: omnívoros - herbivoros o carnívoros',
'que son las avestruzes: omnívoros - herbivoros o carnívoros',
'que son los osos: omnívoros - herbivoros o carnívoros',
'que son los leopardos: omnívoros - herbivoros o carnívoros',
'que son los lobos: omnívoros - herbivoros o carnívoros',
'como se llama el triángulo que tiene tres lados desiguales',
'como se llama el triángulo que tiene dos lados iguales y uno desigual',
'cuantos medio kilo hay en un kilo',
'cuantos medio kilo hay en dos kilo',
'cuantos medio kilo hay en tres kilo',
'cuantos medio kilo hay en cuatro kilo',
'cuantos medio kilo hay en cinco kilo',
'los colores primarios son el azul el amarillo y el.. ',
'los colores primarios son el amarillo, el rojo y el.. ',
'los colores primarios son el rojo el azul y el.. ',
'el color verde es un color primario - si o no',
'el color celeste es un color primario - si o no',
'el color violeta es un color primario - si o no',
'el color rojo es un color primario - si o no',
'el color azul es un color primario - si o no',
'como se llama la fobia a los payasos',
'quien fue el inventor de la Coca-Cola',
'Qué popular empresa tiene los derechos comerciales del tablero Ouija',
'Cuál es el país más pequeño del mundo',
'De qué país es originario el cóctel mojito',
'En dónde se encuentra el monte Fuji',
'En qué año murió Freddy Mercury',
'Cuántos huesos tiene un adulto promedio',
'que es mas pequeño un edificio o un perro',
'que es mas pequeño un gato o una jirafa',
'que es mas pequeño la luna o el sol',
'la palabra - bebes - es plural o singular',
'la palabra - avion - es plural o singular',
'la palabra - barcos- es plural o singular',
'la palabra - barrilete - es plural o singular',
'la palabra - bibliotecas - es plural o singular',
'la palabra - boca - es plural o singular',
'la palabra - bombones - es plural o singular',
'la palabra - bicicleta - es plural o singular',
'la palabra - cajas - es plural o singular',
'la palabra - calcetin - es plural o singular',
'la palabra - calculadoras - es plural o singular',
'la palabra - caldo- es plural o singular',
'la palabra -calles - es plural o singular',
'la palabra - cama - es plural o singular',
'la palabra - caminos - es plural o singular',
'la palabra - camisa- es plural o singular',
'la palabra - campos- es plural o singular',
'la palabra -capa - es plural o singular',
'la palabra - caras- es plural o singular',
'la palabra - campana- es plural o singular',
'la palabra - cámaras - es plural o singular',
'la palabra - camara - es plural o singular',
'la palabra - campanas- es plural o singular',
'la palabra - cara - es plural o singular',
'la palabra - capas - es plural o singular',
'la palabra - campo- es plural o singular',
'la palabra - camisas- es plural o singular',
'la palabra - camino- es plural o singular',
'la palabra - camas- es plural o singular',
'la palabra - calle - es plural o singular',
'la palabra - caldos - es plural o singular',
'cuantas horas tiene dos dia',
'cuantas horas tiene tres dias',
'cuantas horas tiene cuatro dias',
'cuantas horas tiene cinco dias',
'cuantos minutos tiene una hora',
'cuantos minutos tiene dos horas',
'cuantos minutos tiene tres horas',
'cuantos minutos tiene cuatro horas',
'cuantos dias tiene una semana',
'la palabra ángel es esdrujula grave o aguda',
'la palabra cóndor  es esdrujula grave o aguda',
'la palabra fácil  es esdrujula grave o aguda',
'la palabra fósil es esdrujula grave o aguda',
'la palabra símil  es esdrujula grave o aguda',
'la palabra tóner es esdrujula grave o aguda',
'la palabra  récord es esdrujula grave o aguda',
'la palabra carácter es esdrujula grave o aguda',
'la palabra mármol es esdrujula grave o aguda',
'la palabra nácar es esdrujula grave o aguda',
'la palabra póster es esdrujula grave o aguda',
'la palabra cárcel es esdrujula grave o aguda',
'la palabra además  es esdrújula grave o aguda',
'la palabra ají  es esdrújula grave o aguda',
'la palabra mamá  es esdrújula grave o aguda',
'la palabra maní  es esdrújula grave o aguda',
'la palabra sofá  es esdrújula grave o aguda',
'la palabra tacón  es esdrújula grave o aguda',
'la palabra animal  es esdrújula grave o aguda',
'la palabra calor  es esdrújula grave o aguda',
'la palabra pared  es esdrújula grave o aguda',
'la palabra pesar  es esdrújula grave o aguda',
'la palabra reloj  es esdrújula grave o aguda',
'la palabra salud  es esdrújula grave o aguda',
'la palabra señor  es esdrújula grave o aguda',
'la palabra  ábaco  es esdrujula grave o aguda',
'la palabra  brújula  es esdrujula grave o aguda',
'la palabra  cámara es esdrujula grave o aguda',
'la palabra  esdrújula es esdrujula grave o aguda',
'la palabra médico es esdrujula grave o aguda',
'la palabra  oxígeno es esdrujula grave o aguda',
'la palabra  pájaros es esdrujula grave o aguda',
'la palabra  pirámide es esdrujula grave o aguda',
'cual es el antonimo de bonito',
'cual es el antonimo de cálido',
'cual es el antonimo de cerrar',
'cual es el antonimo de claro',
'cual es el antonimo de comodo',
'cual es el antonimo de completo',
'cual es el antonimo de comprar',
'cual es el antonimo de continuar',
'cual es el antonimo de crear',
'cual es el antonimo de flaco',
'cual es el antonimo de grande',
'cual es el antonimo de fácil',
'cual es el antonimo de mentira',
'cual es el antonimo de veloz',
'cual es el antonimo de triunfo',
'cual es el antonimo de sumar',
'cual es el sinónimo de iluminar',
'cual es el sinónimo de importe',
'cual es el sinónimo de increíble',
'cual es el sinónimo de insulto',
'cual es el sinónimo de inteligencia',
'cual es el sinónimo de junta',
'cual es el sinónimo de labor',
'cual es el sinónimo de óleo',
'cual es el sinónimo de orar',
'cual es el sinónimo de página',
'cual es el sinónimo de parar',
'cual es el sinónimo de paz',
'cual es el sinónimo de pelo',
'Qué selección de fútbol ha ganado más Mundiales',
'Qué entrenador argentino es conocido como - el cholo- ',
'en qué país ganó Alemania su primer Mundial',
'Cómo se llama el estadio del Bayern de Munich',
'Qué equipo de la Premier League tiene más ligas ganadas',
'En qué club italiano jugó Diego Maradona',
'el -saxofón - es un instrumento de viento cuerda o percusion',
'el -flauta - es un instrumento de viento cuerda o percusion',
'- clarinete  - es un instrumento de viento cuerda o percusion',
'-trompeta  - es un instrumento de viento cuerda o percusion',
'el -oboe - es un instrumento de viento cuerda o percusion',
' - guitarra - es un instrumento de viento cuerda o percusion',
'el -  arpa - es un instrumento de viento cuerda o percusion',
'el - violín - es un instrumento de viento cuerda o percusion',
'el -piano - es un instrumento de viento cuerda o percusion',
'el -timbal,- es un instrumento de viento cuerda o percusion',
'el -  tambor - es un instrumento de viento cuerda o percusion',
' - platillos - es un instrumento de viento cuerda o percusion',
'el -bombo - es un instrumento de viento cuerda o percusion',
'Berlín es un sustantivo propio o comun',
'Lima es un sustantivo propio o comun',
'Quito es un sustantivo propio o comun',
'Bogotá es un sustantivo propio o comun',
'Liverpool es un sustantivo propio o comun',
'Río de Janeiro es un sustantivo propio o comun',
'Brasilia es un sustantivo propio o comun',
'Londres es un sustantivo propio o comun',
'Roma es un sustantivo propio o comun',
'Buenos Aires es un sustantivo propio o comun',
'Madrid es un sustantivo propio o comun',
'Rosario es un sustantivo propio o comun',
'Cancún es un sustantivo propio o comun',
'Manila es un sustantivo propio o comun',
'Salta es un sustantivo propio o comun',
'Antonia es un sustantivo propio o comun',
'Juana es un sustantivo propio o comun',
'Noé es un sustantivo propio o comun',
'Antonio es un sustantivo propio o comun',
'Juano es un sustantivo propio o comun',
'Noelia es un sustantivo propio o comun',
'abuelo es un sustantivo propio o comun',
'palo es un sustantivo propio o comun',
'satélite es un sustantivo propio o comun',
'templo es un sustantivo propio o comun',
'lentes	 es un sustantivo propio o comun',
'bolígrafo es un sustantivo propio o comun',
'plato es un sustantivo propio o comun',
'nube es un sustantivo propio o comun',
'gobierno es un sustantivo propio o comun',
'botella es un sustantivo propio o comun',
'Castillo es un sustantivo propio o comun',
'enano es un sustantivo propio o comun',
'Qué se celebra el 1 de mayo',
' que se celebra el 1 de enero',
'Qué se celebra el día 8 de diciembre',
'que se celebra el dia 29 de abril',
'que se celebra el dia  8 de marzo',
'que se celebra el dia 21 de agosto',
'que se celebra el dia 19 de junio',
'que se celebra el dia 11 de septiembre',
'Cuál fue el primer país en aprobar el sufragio femenino',
'Cuál era la ciudad hogar de Marco Polo',
'En qué año tuvo lugar el genocidio de Ruanda',
'Quién fue el primer presidente de la democracia española después del franquismo',
'Qué reina británica fue hija de los Reyes Católicos',
'Por qué nombre se conocía a la traductora e intérprete del conquistador Hernán Cortés en tierras aztecas',
'En qué año se disolvió la Unión Soviética',
'En qué ciudad se entrevistaron Hitler y Franco',
'De qué país se independizó Eslovenia',
'Quién era el emperador de Roma cuando murió Jesús de Nazaret',
'en qué país de Europa se habla el magyar',
'En qué país se encuentra el pico Aconcagua',
'Cuál es el país más visitado del mundo',
'Por cuántos estados está formado Estados Unidos',
'Quién pintó- el Guernica-',
'Qué italiano puso música al Othelo de Shakespeare',
'Con qué nombre firmaba Van Gogh sus obras',
'Qué filósofo creó -El mito de la caverna-',
'En qué mes el Sol está más cerca de la Tierra',
'En qué lado del cuerpo está el hígado - derecho o izquierdo-',
'Cuántos elementos tiene la tabla periódica',
'Qué gas de la atmósfera nos protege de la radiación ultravioleta',
'Qué elemento está presente en absolutamente todas las moléculas orgánicas',
'Cómo se llama el proceso celular en el que una célula se divide para dar lugar a dos células hijas iguales',
'la nariz de quien se alargaba cada vez que mentia',
'como se llama el hada de peter pan',
'si congelas el agua que obtienes',
'de que colores son las estrellas en la bandera estadounidense',
'donde vive el presidente de los ee.uu. mientras esta en el cargo',
'cuantos planetas hay en nuestro sistema solar',
'que oceano esta en frente a la costa de california'
]
global.logi = [
'funda',
'cantante',
'antartida',
'1969',
'actor',
'60',
'4',
'24',
'pobre',
'pentagrama',
'si',
'equilatero',
'verbo',
'narrador',
'good afternoon',
'pulmones',
'tilde',
'81',
'rio volga',
'branquias',
'rio amazonas',
'agua',
'paris',
'de la madera',
'america',
'paris',
'miguel de cervantes',
'rusia',
'producto',
'guepardo',
'8',
'la tierra',
'omnivoros',
'1492',
'ecuador',
'rio nilo',
'rio tajo',
'dirham',
'ulan bator',
'cafe',
'1939',
'atletismo',
'jupiter',
'china',
'rodio',
'estocolmo',
'zoologia',
'mandarin',
'mir',
'cobre',
'pancreas',
'teheran',
'telescopio',
'atomo',
'murcielago',
'32',
'chile',
'judas',
'cartografia',
'alexander fleming',
'18',
'si',
'no',
'no',
'1945',
'cantante',
'fotosintesis',
'escama',
'no',
'copenhague',
'latin',
'no',
'sylvester stallone',
'carne',
'camboya',
'13',
'si',
'hello',
'no',
'si',
'si',
'si',
'si',
'si',
'si',
'no',
'no',
'no',
'8',
'12',
'16',
'20',
'24',
'28',
'32',
'no',
'no',
'no',
'no',
'no',
'si',
'si',
'si',
'si',
'si',
'mercurio',
'venus',
'marte',
'urano',
'saturno',
'neptuno',
'herbivoros',
'herbivoros',
'herbivoros',
'herbivoros',
'herbivoros',
'herbivoros',
'herbivoros',
'omnivoros',
'omnivoros',
'omnivoros',
'carnivoros',
'carnivoros',
'carnivoros',
'escaleno',
'isosceles',
'2',
'4',
'6',
'8',
'10',
'rojo',
'azul',
'amarillo',
'no',
'no',
'no',
'si',
'si',
'coulrofobia',
'john stith pemberton',
'hasbro',
'ciudad del vaticano',
'cuba',
'japon',
'1991',
'206',
'perro',
'gato',
'luna',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'singular',
'plural',
'48',
'72',
'96',
'120',
'60',
'120',
'180',
'240',
'7',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'grave',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'aguda',
'esdrujula',
'esdrujula',
'esdrujula',
'esdrujula',
'esdrujula',
'esdrujula',
'esdrujula',
'esdrujula',
'feo',
'frio',
'abrir',
'oscuro',
'incomodo',
'incompleto',
'vender',
'seguir',
'destruir',
'gordo',
'pequeño',
'dificil',
'verdad',
'lento',
'derrota',
'restar',
'alumbrar',
'valor',
'impresionante',
'agravio',
'sabiduria',
'reunion',
'trabajo',
'aceite',
'rezar',
'hoja',
'detener',
'tranquilidad',
'cabello',
'brasil',
'diego simeone',
'suiza',
'allianz arena',
'manchester united',
'napoli',
'viento',
'viento',
'viento',
'viento',
'viento',
'cuerda',
'cuerda',
'cuerda',
'cuerda',
'percusion',
'percusion',
'percusion',
'percusion',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'propio',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'comun',
'dia del trabajador',
'año nuevo',
'dia de la inmaculada concepcion',
'dia del animal',
'dia de la mujer',
'dia del niño',
'dia del padre',
'dia del abuelo',
'nueva zelanda',
'venecia',
'1994',
'adolfo suarez',
'catalina de aragon',
'malinche',
'1991',
'hendaya',
'yugoslavia',
'tiberio',
'hungria',
'argentina',
'francia',
'50',
'pablo picasso',
'verdi',
'vincent',
'platon',
'diciembre',
'derecho',
'118',
'ozono',
'carbono',
'mitosis',
'pinocho',
'campanita',
'hielo',
'blanco',
'casa blanca',
'8',
'pacifico'
]
global.ruizdi = 0
global.lll = 0
let lui = 342
let handler = async (m, {conn, usedPrefix}) => {
let veces = global.lll
if (global.lll === 0) {
let Numero = Math.ceil(lui * Math.random())
global.lll += Numero
global.ruizdi += 2


//Numero


let veca = global.lll
//global.lll -= global.lll 
//if (args[0] === global.logi[veca]) return conn.reply(m.chat, `Ganaste `, m)

m.reply(`
*Preguntados:*
*pregunta:* ¿ ${global.yeca[Numero]} ?

Tiempo: 5 minutos
 


`.trim()) 

setTimeout(()=> {
if(global.lll > 1) { global.lll -= global.lll}
if(global.ruizdi > 1) { global.ruizdi -= global.ruizdi}
return 
}, 300000)

//if(typeof global.lll == 'undefined' || 'NaN') {
 // global.lll = 0
 // }
}

else{

let veces = global.lll
global.ruizdi += 1
//Respuesta : ${global.logi[veces]}
//Respuesta: ${global.logi[veces]}
  m.reply(`

*pregunta:* ¿ ${global.yeca[veces]} ?

tiempo: 5 minutos
Jugadores en linea: ${global.ruizdi}

Todo minusculas y sin acento
las respuestas tienen que ser exactas

Si es correcto *Ganarás*!

`.trim()) 


} 

}
handler.help = ['preguntados']
handler.tags = ['game']
handler.command = /^(pre(guntados)?)$/i

module.exports = handler






